controller: {}
workers: 
- type: router
  realms: 
  - name: ot_realm
    roles: 
    - name: anonymous
      permissions: 
      - {call: true, publish: true, register: true, subscribe: true, uri: '*'}
  transports: 
    - type: web
      endpoint: {port: 8080, type: tcp}
      paths:
        /: {directory:  "../../otone_frontend/web", type: static}
        ws: {type: "websocket"}
        config: {directory: "../../otone_frontend/web/config", type: static}
- type: container
  options: {pythonpath: [".."]}
  components: 
    - type: "class"
      classname: "ot_server.ot_server.AppSession"
      realm: "ot_realm"
      transport: 
        type: "websocket"
        endpoint: {port: 8080, host: 127.0.0.1, type: tcp}
        url: "ws://127.0.0.1:8080/ws"

