controller: {}
workers: 
- type: router
  realms: 
  - name: ot_realm
    roles: 
    - name: anonymous
      permissions: 
      - {call: true, publish: true, register: true, subscribe: true, uri: '*'}
  transports: 
    - type: web
      endpoint: {port: 8080, type: tcp}
      paths:
        /: {directory:  "../../otone_frontend/web", type: static}
        ws: {type: "websocket"}

